### ISSUE TITLE
MIT License Violation and Lack of Attribution

### ISSUE THREAD

**Issue by Argusmocny** [maovshao/PLMAlign#1]
We have noticed that several key pieces of code presented in this repository are exact or slightly modified copies of substantial portions of our software - [pLM-BLAST](https://github.com/labstructbioinf/pLM-BLAST). As such, according to the MIT license under which we released our code, it should be labeled accordingly, either by including the original license or at least mentioning it in the copied or modified files and functions. We therefore ask you to correct this error, or we will be forced to take further action, including but not limited to filing a [DMCA notice](https://docs.github.com/en/site-policy/content-removal-policies/dmca-takedown-policy) with Github.

Aside from the violation of the MIT license, we believe that directly copying the work and code of other researchers without proper attribution and presenting it, even with minor modifications, as one's own creative work is an example of scientific misconduct and should be investigated as such. We have therefore expressed our concerns to the Editorial Board of Nature Communications, where this repository was presented in the [PLMSearch: Protein language model powers accurate and fast sequence search for remote homology](https://www.nature.com/articles/s41467-024-46808-5) article.

This issue was added on behalf of all the authors of pLM-BLAST.
 [@MiTRonGTE, @jludwiczak, @staszekdh @vikramalva]

**Comment by maovshao** [comment]
Dear Dr. Argusmocny,

We fully respect the copyright of the pLM-BLAST codes. We apologize for failing to cite the pLM-BLAST codes appropriately in the previous PLMAlign codes, though we have cited the pLM-BLAST paper (reference 48) and compared with it in our work published in Nature Communications. To address this issue, we have made the following changes in the PLMAlign repository.

1、We have updated the MIT license and the corresponding PLMAlign codes to indicate that they were modified from pLM-BLAST (see [the commit "2024.7.3: LICENSE UPDATE"](https://github.com/maovshao/PLMAlign/commit/6fd3f047ca422d72a0fc3e2eb7e1631b04a956d3)). We also cited the pLM-BLAST codes indicated in the updated README (see [the commit "2024.7.3: README UPADTE"](https://github.com/maovshao/PLMAlign/commit/a73d996708bddf52ed8b453e257373f34303d229)).

2、 In our latest update, we have now included the original license and mentioned it in the copied or modified files and functions. Specifically, in addition to including the original license, we have added the following content to the relevant files and functions:
```
# Copyright (c) 2022 Laboratory of Structural Bioinformatics
#
# This file is modified from [https://github.com/labstructbioinf/pLM-BLAST].
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
```
