### ISSUE TITLE
difference output between web sever and local run

### ISSUE THREAD

**Issue by orangeSi** [maovshao/PLMAlign#3]
Hi @maovshao ， I test three way and get different ```score``` as below table:
   ```try1```: run at ```https://dmiip.sjtu.edu.cn/PLMAlign/``` 
   ```try2```: I install at my computer as https://github.com/maovshao/PLMAlign/blob/main/requirements.sh and then run ``` plmalign_pipeline('example/query.fasta', 'example/target.fasta')``` at pipeline.ipynb
    ```try3``` : use ```esm_embedding_generate```

<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

vs | try1 | try2 | try3
-- | -- | -- | --
P0AD96-P0AD96 | 35.781 | 35.78100586 | 418.8266296386719
P0AD96-P15104 | 4.7536 | 5.207385063 | 321.0542907714844
P0AD96-P22768 | 5.1599 | 5.570289135 | 320.22625732421875
P0AD96-P32352 | 2.5494 | 2.760048628 | 317.43475341796875
P0AD96-Q08558 | 3.7734 | 3.853003025 | 317.8677673339844

</body>

</html>

so, what's the reason of above difference?  which one is right? 

Thanks!
Si

**Comment by maovshao** [comment]
Dear Si,

Thank you for your valuable feedback.

Upon reviewing the server code at [[PLMAlign Webserver](https://dmiip.sjtu.edu.cn/PLMAlign/)](https://dmiip.sjtu.edu.cn/PLMAlign/), I discovered that it had not been updated concurrently with the GitHub repository. This version discrepancy resulted in the slight differences observed between your try1 and try2 results.

I have now updated the PLMAlign Webserver to ensure that it is in sync with the latest version on GitHub. Consequently, both the webserver and the GitHub repository will produce identical results moving forward. I recommend using the most recent code from the GitHub repository to ensure accuracy and consistency.

Regarding the discrepancies observed in try3 when using `esm_embedding_generate`, our experiments have demonstrated that generating amino acid-level embeddings with the ProtT5-XL-UniRef50 model yields superior performance in PLMAlign compared to using ESM-1b. This finding is detailed in our paper ([[Nature Communications](https://www.nature.com/articles/s41467-024-46808-5)](https://www.nature.com/articles/s41467-024-46808-5), Supplementary Fig. 8). Therefore, we advise using ProtT5 embeddings, aligning with the default parameters in `pipeline.ipynb`, which is also the configuration employed on our Webserver. The inclusion of ESM-1b in the GitHub repository is intended solely to facilitate the reproducibility of experimental results.

If you have any further questions or require additional assistance, please do not hesitate to reach out.

Best regards,

Wei Liu

**Comment by orangeSi** [comment]
Thanks~ I just rerun ```https://dmiip.sjtu.edu.cn/PLMAlign/``` and get the same score as the try2!
